USE MASTER
GO
DROP DATABASE IF EXISTS TIECCUOI 

CREATE DATABASE TIECCUOI
USE TIECCUOI
GO

CREATE TABLE DATCOC 
(
	MADC VARCHAR(10) NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	MAKH VARCHAR(10) NOT NULL,
	NGAYDC DATETIME,
	MACTDC VARCHAR(10) NOT NULL,
	CONSTRAINT DC_PK PRIMARY KEY (MADC)
)

CREATE TABLE CTDATCOC 
(
	MACTDC VARCHAR(10) NOT NULL,
	MASANH VARCHAR(10) NOT NULL,
	CA INT,
	NGAYTC DATETIME,
	SOTIENC0C INT,
	CONSTRAINT CTDC_PK PRIMARY KEY (MACTDC)
)

CREATE TABLE HOPDONG
(
	MAHD VARCHAR(10) NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	MAKH VARCHAR(10) NOT NULL,
	MACTHD VARCHAR(10) NOT NULL,
	NGAYHD DATETIME,
	MAKM VARCHAR(10),
	CONSTRAINT HD_PK PRIMARY KEY (MAHD)
)

CREATE TABLE CTHOPDONG 
(
	MACTHD VARCHAR(10) NOT NULL,
	TENCODAU NVARCHAR(50) NOT NULL,
	TENCHURE NVARCHAR(50) NOT NULL,
	MASANH VARCHAR(10) NOT NULL,
	CA INT,
	SOBAN DECIMAL(4),
	NGAYTC DATETIME,
	SOTIENCOC INT,
	TONGTIEN INT,
	CONSTRAINT CTHD_PK PRIMARY KEY (MACTHD)
)

CREATE TABLE MENU
(
	MAMA VARCHAR(10) NOT NULL,
	TENMA NVARCHAR(50) NOT NULL,
	HINHANH IMAGE,
	GIATIEN INT NOT NULL,
	MOTA NVARCHAR(100),
	CONSTRAINT MENU_PK PRIMARY KEY (MAMA)
)

CREATE TABLE DICHVU
(
	MADV VARCHAR(10) NOT NULL,
	TENDV NVARCHAR(50) NOT NULL,
	HINHANH IMAGE,
	GIATIEN INT NOT NULL,
	MOTA NVARCHAR(100),
	CONSTRAINT DV_PK PRIMARY KEY (MADV)
)

CREATE TABLE KHUYENMAI
(
	MAKM VARCHAR(10) NOT NULL,
	TENKM NVARCHAR(50) NOT NULL,
	HINHANH IMAGE,
	UUDAI INT NOT NULL,
	NGAYBD DATETIME,
	NGAYKT DATETIME,
	MOTA NVARCHAR(100),
	CONSTRAINT KM_PK PRIMARY KEY (MAKM)
)

CREATE TABLE SANH 
(
	MASANH VARCHAR(10) NOT NULL,
	TENSANH NVARCHAR(50) NOT NULL,
	HINHANH IMAGE,
	DONGIATT INT,
	MOTA NVARCHAR(100),
	CONSTRAINT SANH_PK PRIMARY KEY (MASANH)
)

CREATE TABLE DSCTMENU
(
	MACTHD VARCHAR(10) NOT NULL,
	MAMA VARCHAR(10) NOT NULL,
	CONSTRAINT DSCTMENU_PK PRIMARY KEY (MACTHD, MAMA)
)

CREATE TABLE DSCTDV
(
	MACTHD VARCHAR(10) NOT NULL,
	MADV VARCHAR(10) NOT NULL,
	CONSTRAINT DSCTDV_PK PRIMARY KEY (MACTHD, MADV)
)

CREATE TABLE KHACHHANG 
(
	MAKH VARCHAR(10) NOT NULL,
	TENKH NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(50),
	DIACHI NVARCHAR(50),
	CONSTRAINT KH_PK PRIMARY KEY (MAKH)
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL,
	TENNV NVARCHAR(50) NOT NULL,
	GT INT,
	CHUCVU VARCHAR,
	MUCLUONG INT,
	THUONG INT,
	CONSTRAINT NV_PK PRIMARY KEY (MANV)
)

CREATE TABLE THANHTOANHD
(
	MAHD VARCHAR(10) NOT NULL,
	MANV VARCHAR(10),
	NGAYTT DATETIME,
	TINHTRANG VARCHAR(1),
	SOTIENPS INT,
	MAPHAT VARCHAR(10),
	CONSTRAINT TTHD_PK PRIMARY KEY(MAHD)
)

CREATE TABLE PHIEUPHAT
(
	MAPHAT VARCHAR(10) NOT NULL,
	SONGAYTRE DECIMAL(4),
	DONGIAPHAT INT,
	SOTIENPHAT INT,
	CONSTRAINT PP_PK PRIMARY KEY(MAPHAT)
)

 ALTER TABLE DATCOC ADD CONSTRAINT DC_MANV_FK FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) 
 ALTER TABLE DATCOC ADD CONSTRAINT DC_MAKH_FK FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH) 
 ALTER TABLE DATCOC ADD CONSTRAINT DC_MACTDC_FK FOREIGN KEY(MACTDC) REFERENCES CTDATCOC(MACTDC) 

 ALTER TABLE CTDATCOC ADD CONSTRAINT CTDATCOC_MASANH_FK FOREIGN KEY(MASANH) REFERENCES SANH(MASANH) 
 
 ALTER TABLE HOPDONG ADD CONSTRAINT HOPDONG_MANV_FK FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) 
 ALTER TABLE HOPDONG ADD CONSTRAINT HOPDONG_MAKH_FK FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
 ALTER TABLE HOPDONG ADD CONSTRAINT HOPDONG_MACTHD_FK FOREIGN KEY(MACTHD) REFERENCES CTHOPDONG(MACTHD)
 ALTER TABLE HOPDONG ADD CONSTRAINT HOPDONG_MAKM_FK FOREIGN KEY(MAKM) REFERENCES KHUYENMAI(MAKM)

 ALTER TABLE CTHOPDONG ADD CONSTRAINT CTHOPDONG_MASANH_FK FOREIGN KEY(MASANH) REFERENCES SANH(MASANH)

 ALTER TABLE DSCTMENU ADD CONSTRAINT DSCTMENU_MACTHD_FK FOREIGN KEY(MACTHD) REFERENCES CTHOPDONG(MACTHD)
 ALTER TABLE DSCTMENU ADD CONSTRAINT DSCTMENU_MAMA_FK FOREIGN KEY(MAMA) REFERENCES MENU(MAMA)

 ALTER TABLE DSCTDV ADD CONSTRAINT DSCTDV_MACTHD_FK FOREIGN KEY(MACTHD) REFERENCES CTHOPDONG(MACTHD)
 ALTER TABLE DSCTDV ADD CONSTRAINT DSCTDV_MADV_FK FOREIGN KEY(MADV) REFERENCES DICHVU(MADV)

 ALTER TABLE THANHTOANHD ADD CONSTRAINT THANHTOANHD_MAHD_FK FOREIGN KEY(MAHD) REFERENCES HOPDONG(MAHD)
 ALTER TABLE THANHTOANHD ADD CONSTRAINT THANHTOANHD_MANV_FK FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
 ALTER TABLE THANHTOANHD ADD CONSTRAINT THANHTOANHD_MAPHAT_FK FOREIGN KEY(MAPHAT) REFERENCES PHIEUPHAT(MAPHAT)

 