//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiecCuoi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDATCOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTDATCOC()
        {
            this.DATCOCs = new HashSet<DATCOC>();
        }
    
        public string MACTDC { get; set; }
        public string MASANH { get; set; }
        public Nullable<int> CA { get; set; }
        public Nullable<System.DateTime> NGAYTC { get; set; }
        public Nullable<int> SOTIENC0C { get; set; }
    
        public virtual SANH SANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATCOC> DATCOCs { get; set; }
    }
}
