//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiecCuoi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATCOC
    {
        public string MADC { get; set; }
        public string MANV { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.DateTime> NGAYDC { get; set; }
        public string MACTDC { get; set; }
    
        public virtual CTDATCOC CTDATCOC { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
