//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiecCuoi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string MAHD { get; set; }
        public string MANV { get; set; }
        public string MAKH { get; set; }
        public string MACTHD { get; set; }
        public Nullable<System.DateTime> NGAYHD { get; set; }
        public string MAKM { get; set; }
    
        public virtual CTHOPDONG CTHOPDONG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THANHTOANHD THANHTOANHD { get; set; }
    }
}
