//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiecCuoi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUPHAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUPHAT()
        {
            this.THANHTOANHDs = new HashSet<THANHTOANHD>();
        }
    
        public string MAPHAT { get; set; }
        public Nullable<decimal> SONGAYTRE { get; set; }
        public Nullable<int> DONGIAPHAT { get; set; }
        public Nullable<int> SOTIENPHAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOANHD> THANHTOANHDs { get; set; }
    }
}
