//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiecCuoi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOANHD
    {
        public string MAHD { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> NGAYTT { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<int> SOTIENPS { get; set; }
        public string MAPHAT { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEUPHAT PHIEUPHAT { get; set; }
    }
}
